#!/bin/bash -e
# This script publishes the core of Scala to maven for use as locker downstream,
# and saves the relevant properties used in its build artifacts, versions.properties.
# (This means we'll use locker instead of quick downstream in dbuild.
#  The only downside is that backend improvements don't improve compiler performance itself until they are in STARR).
# The version is suffixed with "-${sha:0:7}-SNAPSHOT"

baseDir=${WORKSPACE-`pwd`}
scriptsDir="$baseDir/scripts"
. $scriptsDir/common

case $prDryRun in
  yep)
    echo "DRY RUN"
    mkdir -p build/pack ; mkdir -p dists/maven/latest
    ;;
  *)
      $SBT_CMD --warn "setupPublishCore $prRepoUrl" dist/mkQuick
      mkdir target/tmp
      ./build/quick/bin/scalac -d target/tmp $(find src/compiler -name '*.scala')
    ;;
esac
